# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=50)),
                ('photo', models.ImageField(upload_to='patient_photos')),
                ('UUID', models.CharField(default='UUID', max_length=50)),
                ('remark', models.CharField(default='Remark', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(default='Medication', max_length=255)),
                ('quantity', models.CharField(default='Quantity', max_length=50)),
                ('interval', models.CharField(choices=[('ONE', '1 time a day'), ('TWO', '2 times a day'), ('THREE', '3 times a day'), ('FOUR', '4 times a day'), ('FIVE', '5 times a day')], default='Time', max_length=5)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docnotes.Patients')),
            ],
        ),
    ]
