# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docnotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='name',
            new_name='patient',
        ),
    ]
