# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docnotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(default='Medication', max_length=255)),
                ('quantity', models.CharField(default='Quantity', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='patients',
            name='UUID',
            field=models.CharField(default='UUID', max_length=50),
        ),
        migrations.AddField(
            model_name='patients',
            name='remark',
            field=models.CharField(default='Remark', max_length=255),
        ),
        migrations.AlterField(
            model_name='patients',
            name='name',
            field=models.CharField(default='Name', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docnotes.Patients'),
        ),
    ]
