# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('docnotes', '0005_patients_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='UUID',
        ),
        migrations.AlterField(
            model_name='patients',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
