# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docnotes', '0008_prescription_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='interval',
            field=models.CharField(choices=[('1 time a day', '1 time a day'), ('2 times a day', '2 times a day'), ('3 times a day', '3 times a day'), ('4 times a day', '4 times a day'), ('5 times a day', '5 times a day'), ('6 times a day', '6 times a day')], default='Time', max_length=20),
        ),
    ]
