# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docnotes', '0009_auto_20160604_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='schedule',
            field=models.CharField(default='completed', max_length=255),
        ),
    ]
