# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docnotes', '0011_patients_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='device_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
