# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docnotes', '0014_auto_20160604_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='deviceid',
            new_name='id',
        ),
        migrations.AddField(
            model_name='patients',
            name='device_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
