# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docnotes', '0015_auto_20160604_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='id',
        ),
        migrations.AlterField(
            model_name='patients',
            name='device_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
