# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docnotes', '0016_auto_20160604_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='photo',
            field=models.ImageField(blank=True, upload_to='patient_photos'),
        ),
    ]
