# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docnotes', '0019_auto_20160604_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='time_inverval',
            new_name='time_interval',
        ),
    ]
